### PR TITLE
Always drain the stderror pipe to prevent hangs on Linux

### LINKED ISSUE #47: Hanging regression in hsc2hs 0.68.7
Needs more investigation; the following will hang indefinitely

```
$ cabal get bindings-common-1.3.4
$ cd bindings-common-1.3.4
$ /opt/ghc/8.10.1/bin/hsc2hs -v -I src ./src/Bindings/C/Ctype.hsc
Executing: (@./src/Bindings/C/hsc2hscall18234-0.rsp) /usr/bin/cc -c ./src/Bindings/C/Ctype_hsc_make.c -o ./src/Bindings/C/Ctype_hsc_make.o -Isrc -I/opt/ghc/8.10.1/lib/ghc-8.10.1/include/
```

### PR DESCRIPTION
**Pull request by Mistuke**
Fixes #47

Can you try this out @phadej
/cc @hvr

### CODE REVIEW

File: Common.hs [hunk 1]
```diff
@@ -72,11 +72,11 @@ rawSystemWithStdOutL outDir outBase action flg prog args outFile = withResponseF
 #endif
          }
   exitStatus <- waitForProcess process
+  errdata <- maybeReadHandle progerr
```
Comment (phadej) [inline Common.hs:75]: My gut feeling says that this should be before `waitForProcess`.
When process terminates it will close the file descriptor. Then `waitForProcess` won't block either.
Or the process might close FD early, then `waitForProcess` will block, but there is no output to drain.

Comment (Mistuke) [reply Common.hs:75]: How would putting it before `waitForProcess` work as there might not have been anything written yet to read.

Comment (phadej) [reply Common.hs:75]: The process is already spawned by `createProcess`, so it will write to the other side of the pipe.

I tried this patch as is, it doesn't work. 

With below patch on top, the #47 case works (i.e. it terminates, even in that case unsuccessfully).

```diff
diff --git a/Common.hs b/Common.hs
index 0a582dc..47d3fac 100644
--- a/Common.hs
+++ b/Common.hs
@@ -43,8 +43,8 @@ rawSystemL outDir outBase action flg prog args = withResponseFile outDir outBase
     , use_process_jobs = True
 #endif
     }
-  exitStatus <- waitForProcess ph
   errdata <- maybeReadHandle progerr
+  exitStatus <- waitForProcess ph
   case exitStatus of
     ExitFailure exitCode ->
       do die $ action ++ " failed "
@@ -71,8 +71,8 @@ rawSystemWithStdOutL outDir outBase action flg prog args outFile = withResponseF
          , use_process_jobs = True
 #endif
          }
-  exitStatus <- waitForProcess process
   errdata <- maybeReadHandle progerr
+  exitStatus <- waitForProcess process
   hClose hOut
   case exitStatus of
     ExitFailure exitCode ->
@@ -86,7 +86,14 @@ rawSystemWithStdOutL outDir outBase action flg prog args outFile = withResponseF
 
 maybeReadHandle :: Maybe Handle -> IO String
 maybeReadHandle Nothing  = return "<no data>"
-maybeReadHandle (Just h) = hGetContents h
+maybeReadHandle (Just h) = do
+    str <- hGetContents h
+    -- Because of the lazy IO, hGetContents doesn't actually drain handle.
+    Exception.evaluate (rnf str `seq` str)
+  where
+    rnf :: String -> ()
+    rnf []     = ()
+    rnf (c:cs) = c `seq` rnf cs
 
```

**Comment by Mistuke** [comment]
huh, did we never fix this? @hvr @bgamari @RyanGlScott

File: Common.hs [hunk 2]
```diff
@@ -86,7 +86,14 @@ rawSystemWithStdOutL outDir outBase action flg prog args outFile = withResponseF
 
 maybeReadHandle :: Maybe Handle -> IO String
 maybeReadHandle Nothing  = return "<no data>"
-maybeReadHandle (Just h) = hGetContents h
+maybeReadHandle (Just h) = do
+    str <- hGetContents h
+    -- Because of the lazy IO, hGetContents doesn't actually drain handle.
```
Comment (bgamari) [inline Common.hs:91]: More detail is needed here. Explain why it matters if the handle isn't drained with a reference to the ticket.

Comment (Mistuke) [reply Common.hs:94]: Comment added

**Comment by phadej** [comment]
I think this should be merge, ping @bgamari

**Review by bgamari — APPROVED** [review]
